
package fr.afcepf.dja.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceTvaImplService", targetNamespace = "http://ws.dja.afcepf.fr/", wsdlLocation = "http://localhost:8080/serverSoap/ws/tva?wsdl")
public class ServiceTvaImplService
    extends Service
{

    private final static URL SERVICETVAIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICETVAIMPLSERVICE_EXCEPTION;
    private final static QName SERVICETVAIMPLSERVICE_QNAME = new QName("http://ws.dja.afcepf.fr/", "ServiceTvaImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/serverSoap/ws/tva?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICETVAIMPLSERVICE_WSDL_LOCATION = url;
        SERVICETVAIMPLSERVICE_EXCEPTION = e;
    }

    public ServiceTvaImplService() {
        super(__getWsdlLocation(), SERVICETVAIMPLSERVICE_QNAME);
    }

    public ServiceTvaImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICETVAIMPLSERVICE_QNAME, features);
    }

    public ServiceTvaImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICETVAIMPLSERVICE_QNAME);
    }

    public ServiceTvaImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICETVAIMPLSERVICE_QNAME, features);
    }

    public ServiceTvaImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceTvaImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceTva
     */
    @WebEndpoint(name = "ServiceTvaImplPort")
    public ServiceTva getServiceTvaImplPort() {
        return super.getPort(new QName("http://ws.dja.afcepf.fr/", "ServiceTvaImplPort"), ServiceTva.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceTva
     */
    @WebEndpoint(name = "ServiceTvaImplPort")
    public ServiceTva getServiceTvaImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.dja.afcepf.fr/", "ServiceTvaImplPort"), ServiceTva.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICETVAIMPLSERVICE_EXCEPTION!= null) {
            throw SERVICETVAIMPLSERVICE_EXCEPTION;
        }
        return SERVICETVAIMPLSERVICE_WSDL_LOCATION;
    }

}
