
package fr.afcepf.dja.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceTva", targetNamespace = "http://ws.dja.afcepf.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceTva {


    /**
     * 
     * @param taux
     * @param ht
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "tva", targetNamespace = "http://ws.dja.afcepf.fr/", className = "fr.afcepf.dja.ws.Tva")
    @ResponseWrapper(localName = "tvaResponse", targetNamespace = "http://ws.dja.afcepf.fr/", className = "fr.afcepf.dja.ws.TvaResponse")
    @Action(input = "http://ws.dja.afcepf.fr/ServiceTva/tvaRequest", output = "http://ws.dja.afcepf.fr/ServiceTva/tvaResponse")
    public double tva(
        @WebParam(name = "ht", targetNamespace = "")
        double ht,
        @WebParam(name = "taux", targetNamespace = "")
        double taux);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAuteur", targetNamespace = "http://ws.dja.afcepf.fr/", className = "fr.afcepf.dja.ws.GetAuteur")
    @ResponseWrapper(localName = "getAuteurResponse", targetNamespace = "http://ws.dja.afcepf.fr/", className = "fr.afcepf.dja.ws.GetAuteurResponse")
    @Action(input = "http://ws.dja.afcepf.fr/ServiceTva/getAuteurRequest", output = "http://ws.dja.afcepf.fr/ServiceTva/getAuteurResponse")
    public String getAuteur();

}
